---
- name: Deploy WAR file
  hosts: maven
  tasks:
    - name: copy war to container
      command: "sudo docker cp /home/ubuntu/java-code/devops/target/devops-1.0-SNAPSHOT.war tomcat:/usr/local/tomcat/webapps/devops.war"
    - name: Restart container
      command: "sudo docker restart tomcat"  
