---
- name: mysql setup
  block:
    - name: Install MySql
      apt:
        name: mysql-server
        state: present

    - name: Create database user with name 'bob' and password '12345' with all database privileges
      community.mysql.mysql_user:
        name: bob
        password: 12345
        priv: '*.*:ALL'
        state: present
    - name: Create a new database with name 'bobdata'
      community.mysql.mysql_db:
        name: wordpress
        state: present
